//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cz.uhk.stormida;

import java.util.List;
import Model.Idea;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;
import cz.uhk.stormida.R.id;

public final class Ideas_
    extends Ideas
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        etIdea = ((EditText) findViewById(id.etIdea));
        tvTitle = ((TextView) findViewById(id.tvTitle));
        lvIdeas = ((ListView) findViewById(id.lvIdeas));
        {
            View view = findViewById(id.btAdd);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Ideas_.this.add();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btDownload);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Ideas_.this.download();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static Ideas_.IntentBuilder_ intent(Context context) {
        return new Ideas_.IntentBuilder_(context);
    }

    @Override
    public void showToast(final CharSequence msg) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    Ideas_.super.showToast(msg);
                } catch (RuntimeException e) {
                    Log.e("Ideas_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void bindData(final List<Idea> ideas) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    Ideas_.super.bindData(ideas);
                } catch (RuntimeException e) {
                    Log.e("Ideas_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void clearET() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    Ideas_.super.clearET();
                } catch (RuntimeException e) {
                    Log.e("Ideas_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Ideas_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Ideas_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
